### ISSUE TITLE
NYC output is empty with mocha installed globally

### ISSUE THREAD

**Issue by Antonius-S** [istanbuljs/nyc#1029]
*Extracted from #822*
I experience no coverage output when both nyc and mocha installed globally (in fact, only mocha installation plays role).
Reproducible repo is [here](https://github.com/Antonius-S/Nyc_test)
Env:
Windows 7
Node 10.15.1
Nyc 13.3.0
Mocha 6.0.2

```
D:\Projects\nyc-test>nyc mocha


  √ should have tests

  1 passing (39ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

D:\Projects\nyc-test>npm i mocha

(...) skipped 

D:\Projects\nyc-test>nyc node_modules\.bin\mocha

  √ should have tests

  1 passing (39ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 stub.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by coreyfarrell** [comment]
This repo seems to work on Linux.  Is this a Windows specific issue?  I was able to get coverage by running with globally installed nyc and mocha.

**Comment by Antonius-S** [comment]
Probably it's Windows specific. I suspect the reason of this issue is something very dumb, like file paths or similar.

**Comment by worc** [comment]
output is also empty on mac, it's probably not windows-specific

**Comment by Antonius-S** [comment]
FWIW: I experienced troubles launching mocha tests from VSCode with the above config so I created a workaround, see https://github.com/Antonius-S/Node_Articles/tree/master/Global_nyc_and_mocha

**Comment by worc** [comment]
another workaround i put together yesterday, which might make people cringe, is to use npm to call the test runners. `yarn run coverage` expands into `nyc npm run test` which expands into `nyc npm run test-unit && npm run test-integration`.

it seems the issue is yarn isn't bubbling up information from the test runs to nyc. but npm can do it.

**Comment by coreyfarrell** [comment]
@Antonius-S are you using yarn?  If so please see if this issue can be reproduced with npm.

**Comment by Antonius-S** [comment]
@coreyfarrell  no I use npm

**Comment by chankamlam** [comment]
<img width="238" alt="屏幕快照 2019-03-29 上午2 24 48" src="https://user-images.githubusercontent.com/9009522/55183087-0de70b80-51ca-11e9-80c1-03022a1a0503.png">
<img width="595" alt="屏幕快照 2019-03-29 上午2 24 33" src="https://user-images.githubusercontent.com/9009522/55183103-16d7dd00-51ca-11e9-9be6-481c18dc7fb6.png">

some problem with me , empty table showing, I am using Mac OS

**Comment by chankamlam** [comment]
fixed by https://github.com/istanbuljs/nyc/issues/822#issuecomment-402435832

**Comment by worc** [comment]
that's not quite a fix, is it? it's more of a workaround to exit mocha cleanly?

**Comment by Antonius-S** [comment]
> fixed by [#822 (comment)](https://github.com/istanbuljs/nyc/issues/822#issuecomment-402435832)

Doesn't help in my case.

**Comment by captnseagraves** [comment]
Experiencing this issue as well. Although I have not seen a difference when running locally or globally. I've tried the discussed solutions in other issue threads and have had no luck. 

MacOS Mojave@10.14.1,
npm@6.4.1, 
mocha@6.1.4,
nyc@14.0.0

**Comment by bcoe** [comment]
@captnseagraves could you create a different PR, with a repo that reproduces your issue? I think that you're probably bumping into something slightly different, this issue specifically relates to a globally installed version of mocha.

**Comment by bcoe** [comment]
we make an effort not to include files when they're outside the directory that is under test, I have a suspicion that this might be the root cause of this bug ... feature? If anyone is interested in taking a look, I would look for our logic that excludes files outside the test directory, and remove it temporarily -- if this does turn out to be the issue, maybe we could add a config option for this.

**Comment by Antonius-S** [comment]
> we make an effort not to include files when they're outside the directory that is under test, I have a suspicion that this might be the root cause of this bug ... feature?

But files under test are in the same folders in both cases. And global mocha shouldn't generate any files outside package under test.

**Comment by marek629** [comment]
Hey, I had the same issue. In my case, following steps helped me:

1. In `package.json` file, scripts entries should be written independently, i.e. your coverage script should looks like:
  ```
  nyc mochapack --reporter nyan app/
  ```
  instead of
  ```
  nyc yarn test
  ```

2. Install [babel-plugin-istanbul](https://www.npmjs.com/package/babel-plugin-istanbul) and configure it in `.babelrc` file

I hope that my solution would helpful for you

**Comment by NearHuscarl** [comment]
Can confirm @marek629 solution works for me. In my case, I just need to change from
```json
    "test": "mocha -r ts-node/register test/**/*.test.{ts,tsx}",
    "cover": "nyc yarn test",
```
to
```json
    "cover": "nyc mocha -r ts-node/register test/**/*.test.{ts,tsx}",
```

**Comment by shivashanmugam** [comment]
Same issue , 
While Running `nyc mocha`  
![image](https://user-images.githubusercontent.com/6939456/61709403-cf72ef00-ad6c-11e9-9146-5da2735c5fd8.png)

But while Running `nyc moca
`nyc node_modules/.bin/mocha`
![image](https://user-images.githubusercontent.com/6939456/61709440-e44f8280-ad6c-11e9-8143-bab58122b920.png)



``

**Comment by An-dz** [comment]
After maaaany hours of debugging I finally found the problem. It's the `cmd` and `shell` files and [spawn-wrap](https://github.com/istanbuljs/spawn-wrap).

They check if the node executable is in the same directory as they are, when they are installed as modules they work because there's no node executable there and it then relies on using the one in the PATH, but it's there when installed globally.

That's not a problem on Unix because it uses a symbolic link to the JS file. Unless you use a Windows installation on Unix, then you have the same bug.

My solution right now is to patch `spawn-wrap` with this:
```diff
diff --git a/index.js b/index.js
index 908be7f..306b5ce 100644
--- a/index.js
+++ b/index.js
@@ -147,6 +147,21 @@ function setup(argv, env) {
     fs.writeFileSync(path.join(workingDir, cmdname), shim)
     fs.chmodSync(path.join(workingDir, cmdname), '0755')
   }
+  if (cmdname === 'node') {
+    var nodePath = path.dirname(process.execPath)
+    var cmds = JSON.parse(env.NYC_CONFIG)._
+    cmds.forEach((cmd) => {
+      var filepath = path.resolve(nodePath, cmd)
+      if (fs.existsSync(filepath + '.cmd')) {
+        var windows = fs.readFileSync(filepath + '.cmd', 'utf8')
+        var unix = fs.readFileSync(filepath, 'utf8')
+        fs.writeFileSync(workingDir + '/' + cmd + '.cmd', newShim.replace('"%_prog%"  "%dp0%', '"%_prog%"  "' + nodePath))
+        fs.chmodSync(workingDir + '/' + cmd + '.cmd', '0755')
+        fs.writeFileSync(workingDir + '/' + cmd, newShim.replace('"$basedir/node"  "$basedir', '"$basedir/node"  "' + nodePath))
+        fs.chmodSync(workingDir + '/' + cmd, '0755')
+      }
+    })
+  }
   fs.writeFileSync(path.join(workingDir, 'settings.json'), settings)
 
   return workingDir
```

It's a very dirty solution honestly but haven't put much effort.

**Comment by An-dz** [comment]
Done. It's pull request [#104 on spawn-wrap](https://github.com/istanbuljs/spawn-wrap/pull/104).

**Comment by coreyfarrell** [comment]
Please retest using nyc 15 which replaces spawn-wrap with another method of wrapping child processes.

**Comment by An-dz** [comment]
Just used nyc 15 with [AVA](https://github.com/avajs/ava) and it's working.

**Comment by coreyfarrell** [comment]
If others are still experiencing this issue with nyc 15 please comment with a link to a reproduction and we can reopen.

**Comment by RagiRavindran** [comment]
I am having this same issue. Sorry, I can't post the link to my reproduction.
![image](https://user-images.githubusercontent.com/47990319/93003493-d0607480-f55c-11ea-935d-61e62a0fd14c.png)

**Comment by premranderia** [comment]
+1 with same Issue, upgraded from nyc 12.x.x to 15.1.0 and added the .nycrc file and empty coverage

```
{
  "include": ["dist/app/**/*.js"],
  "exclude": ["dist/app/**/*.spec.js"],
  "reporter": ["html", "cobertura", "text-summary"],
  "all": true,
  "report-dir": "./target/coverage"
}
```

**Comment by RagiRavindran** [comment]
I got coverage after separating app.listen() to another file.
